package pipeline;

import java.util.ArrayList;
import java.util.List;

public class PLProcessorData {
	
	// NOTE: This class should render the CoverageData class obsolete.
	
	/*
	 * TODO: Serialize and expose all this data.
	 */
	
	// Generated by initial processor.
	public List<DCPath> allDCPaths;
	
	// Just an idea:
	// A list of each line, pretty printed and indented, which can be easily
	// converted to JSON and used to generate the source code displays in the
	// HTML documents.
	public List<String> prettyPrintedSourceCode;
	
	// Generated by test interpreters.
	public List<DCPath> coveredDCPaths;
	public List<Integer> coveredStatements;
	
	// The output coverage data. These should just be subsets of what's above.
	// Generated by coverage tests.
	
	// NOTE: There is no need for extra data in statement coverage, because
	// the list of coveredStatements (from above) is sufficient.
	
	// Data Flow
	public List<DCPath> coveredForAllDefs;
	public List<DCPath> requiredForAllDefs;
	
	public List<DCPath> coveredForAllCUses;
	public List<DCPath> requiredForAllCUses;
	
	public List<DCPath> coveredForAllPUses;
	public List<DCPath> requiredForAllPUses;
	
	public PLProcessorData() {
		this.allDCPaths = new ArrayList<>();
		this.coveredDCPaths = new ArrayList<>();
		this.coveredStatements = new ArrayList<>();
	}
}
