package pipeline;

import java.util.Map;

import proglang.model.*;
import testlang.model.*;

public class Processor {
	
	/*
	 * Walk through PLProgram and generate the following data:
	 * 	
	 * 	- allDCPaths
	 */
	public ProcessorData processPLFunction(PLFunction<?> prog) {
		/* the data being generated by the processor */
		ProcessorData data = new ProcessorData();
		DCPath path;
		
		/* 
		 * Loop through each of the declarations and function parameters to 
		 * start each DCPath.
		 */
		for (Map.Entry<String, PLDeclaration> entry: prog.getVariables().entrySet()) {
			path = new DCPath(entry.getValue().getLineNum(), entry.getKey());
			
			/*
			 * Loop thorugh each statement in the function and...
			 * 	- Add each statement as a new DCPath if it's a c-use or p-use
			 *  - Start a new DCPath when we've hit a definition.
			 */
			for (PLStatement stmt: prog.getStatements()) {
				processPLStatement(entry, stmt, data, path);
			}
		}
		
		return data;
	}
	
	private void processPLStatement(
			Map.Entry<String, PLDeclaration> entry, 
			PLStatement stmt, 
			ProcessorData data,
			DCPath path
	) {
		if (stmt.hasVariable(entry.getKey())) {
			// Checking c-uses and p-uses
			if (stmt instanceof PLPrint || stmt instanceof PLAssignment) {
				path.setLineTo(stmt.getLineNum());
				path.setCUse(true);
				
				data.allDCPaths.add(path.clone());
			}
			
			// Have we hit a new definition?
			if (stmt instanceof PLAssignment) {
				if (((PLAssignment<?>) stmt).getId().equals(entry.getKey())) {
					path = new DCPath(
							stmt.getLineNum(), 
							((PLAssignment<?>) stmt).getId());
				}
			}
		}
	}
	
	/*
	 * Run through each TLProgram test function and populate the following lists:
	 * 
	 *  - coveredDCPaths;
	 *  - coveredStatements;
	 */
	public void interpret(TLProgram test, PLProgram prog) {
		// TODO implement
	}
	
	/*
	 * Code Coverage generators.
	 */
	public void generateAllDefs(ProcessorData data) {
		// TODO implement
	}

	public void generateAllCUses(ProcessorData data) {
		// TODO implement
	}

	public void generateAllPUses(ProcessorData data) {
		// TODO implement
	}
}
